spring:
  datasource:
    url: ${db.dev.datasource.url}
    username: ${db.dev.datasource.username}
    password: ${db.dev.datasource.password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
